### PR TITLE
Simplifies CMakeLists.txt and package.xml after removing Gazebo plugin

### PR DESCRIPTION
**Pull request by olivier-stasse**
Remove dependencies on roscpp, export Target, remove library.

### CODE REVIEW

**Comment by nim65s** [comment]
Why would you remove the export ? Doing so will prevent dependent projects to declare a dependency on talos-data

**Comment by olivier-stasse** [comment]
I had to do this because there was no target exported, generating a cmake error.
I did not know how to do otherwise.
Any help welcome.

**Comment by nim65s** [comment]
Do you mean that without this PR, on the current devel, something is not configuring / building correctly for you ?

**Comment by olivier-stasse** [comment]
This is slightly different. Thanks to your previous PR we do not need roscpp anymore.
Then the library is not needed anymore, but then we do not have a target.
Maybe I/we should create a target which not an executable nor a library but a target file:
https://cmake.org/cmake/help/latest/command/add_custom_command.html?highlight=target_file
such that we can generate the export ?

**Comment by nim65s** [comment]
The current library is empty, and is actually the target. There is no link between the empty library used as a target you are trying to remove, and roscpp which is not needed anywhere for CMake.

I think you should only make changes in package.xml and keep CMakeLists.txt as it was.

**Comment by olivier-stasse** [comment]
Sorry I forgot about this empty library needed for the cmake target.
I put it back and force-pushed my PR.

**Review by nim65s — APPROVED** [review]

**Comment by nim65s** [comment]
thanks :)

**Pull request merged**
